# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 21:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ManyToManyField(related_name='owned_bucket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('public', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=250)),
                ('friends', models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotifyId', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=250)),
                ('create_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('create_time', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youPotify.Bucket')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songCreater', to=settings.AUTH_USER_MODEL)),
                ('playList', models.ManyToManyField(blank=True, related_name='owned_by', to='youPotify.PlayList')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songReceiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
